version: "3.8"

services:
  mongo-db:
    image: mongo:latest
    container_name: db-mongo
    restart: always 
    environment:
      MONGO_INITDB_ROOT_USERNAME: lappis
      MONGO_INITDB_ROOT_PASSWORD: lappis
    ports: 
      - "27017:27017"