name: sammy-init

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Configurar o Poetry
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.10
    - name: Instalar dependências
      run: |
        python3 -m venv env
        source env/bin/activate
        pip install poetry
    - name: Iniciar sessão do PyPI
      uses: pypa/gh-action-pypi-publish@v1
      with:
        username: __token__
        password: ${{ secrets.PYPI_TOKEN }}
    - name: Build e envio do pacote
      run: |
        poetry build
        poetry publish --build
